---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: static/_pages/homepage.json
  label: Homepage
- type: document
  path: static/_pages/about.json
  label: About
- type: document
  path: static/_pages/contact.json
  label: Contact
- type: document
  path: static/_pages/work.json
  label: Work Landing
- type: directory
  path: static/_projects
  label: Projects
  create: documents
  match: "*.json"
  new_doc_ext: json
- type: document
  path: static/_settings/index.json
  label: Settings
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
