---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: featured_image
  type: file
  config:
    maxSize: 250
  label: Featured Image
- name: caption
  type: text
  config:
    required: false
  label: Caption
- name: role
  type: text
  config:
    required: false
  label: Role
- name: year
  type: text
  config:
    required: false
  label: Year
- name: agency
  type: text
  config:
    required: false
  label: Agency
- name: watermark
  type: file
  config:
    maxSize: 250
  label: Watermark
- name: images
  type: image_gallery
  config: {}
  label: Images
